name = "valencia-api"
main = "index.ts"
compatibility_date = "2024-11-10"

[vars]
TURSO_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzI1NTQxMjksImlkIjoiZjczMGIxZDAtYzYyNy00OWNiLWFmOGEtYWZlZDhlMmUwNThhIn0.DosJ9vfWmAv95AlcKb2djgBz5fybmAE1KZ6Tj1PsDm8slOLJerZo02DFXpR9VYS1WRqPWegDrx8j2Uc4VEx-AA"
TURSO_URL = "libsql://valencia-db-isakfagerlund.turso.io"